### ISSUE TITLE
Should units be hashable?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/scimath#87] opened 2019-05-01 09:06 UTC
At the moment, units are hashable on Python 2 but not on Python 3.

On Python 2 -
```
>>> from scimath.units.length import feet, meters
>>> d = {feet: 'a value', meters: 'another value'}
>>> d
{0.3048*m: 'a value', 1.0*m: 'another value'}
```

On Python 3, creating the dictionary leads to -
```
>>> d = {feet: 'a value', meters: 'another value'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'unit'
```

This is because on Python 3, the definition of the `__eq__` on the `unit` class prevents the inheritance of `__hash__` from `object`.

**Comment by mdickinson** [comment] 2019-05-01 09:10
I'd say yes: I could imagine use-cases with sets of units. The only caveat is that if it's common / supported to modify `scimath.units.unit.unit` objects in-place, then we might want to avoid hashability, but I'd hope that that's not common.

If we just want to get Python 3 behaviour that matches the existing Python 2 behaviour (which may be good enough), then I guess we can add an explicit `__hash__` method that delegates to object's `__hash__`.

**Comment by mdickinson** [comment] 2019-05-01 09:22
It turns out (from offline discussion) that we have real projects failing because of this.

I suggest a two-part solution:

1. As a quick fix, make a PR (with regression test!) to restore Python 2-style hashing to these objects.
2. Consider making a second PR to change from identity-based hashing to content-based hashing.

**Comment by mdickinson** [comment] 2019-05-09 07:25
> 1. As a quick fix, make a PR (with regression test!) to restore Python 2-style hashing to these objects.

Sorry, this is no good. I was somehow disregarding the fact that `unit` defines `__eq__`. Given that we don't have identity-based equality (I'd somehow got my brain into the place where I thought we did have), we can't have identity-based hashing either. That would break the fundamental invariant that if `x == y` is true then `hash(x) == hash(y)` must be true.

**Comment by mdickinson** [comment] 2019-05-09 07:35
Marking this as a bug, because the behaviour in Python 2 is currently broken.
```
>>> from scimath.units.unit import unit
>>> meter = unit(1.0, (1, 0, 0, 0, 0, 0, 0))
>>> metre = unit(1.0, (1, 0, 0, 0, 0, 0, 0))
>>> meter == metre
True
>>> hash(meter) == hash(metre)
False
>>> meter in [metre]
True
>>> meter in {metre}
False
```

**Closed** 2019-05-09 08:29 UTC
Labels: Bug
